### ISSUE TITLE
TypeError: cannot concatenate 'str' and 'NoneType' objects

### ISSUE THREAD

**Issue by xhao79** [ewnit/biliMpv#1]
python bili.py av7138644
http://www.bilibili.com/video/av7138644
http://interface.bilibili.com/playurl?&cid=11644414&from=miniplay&player=1&sign=1687027b596b18c602035568980f096a
403
Forbidden
None
Traceback (most recent call last):
  File "bili.py", line 98, in <module>
    x.play_video()
  File "bili.py", line 89, in play_video
    cmd = 'mpv \'' + url + '\''
TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by cheny1ran** [comment]
居然有人用 很感动 已经修复了 用新版的试试
